#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
spring:
  application:
    name: ${artifactId}
  ai:
    mcp:
      server:
        name: ${spring.application.name}
        version: 1.0.0

  main:
    $symbol_pound 关闭显示启动标志
    banner-mode: off
    $symbol_pound 不会嵌入 web Tomcat
    web-application-type: none
    
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/xxx?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  pattern:
    console:
  file:
    name: ${spring.application.name}.log

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: xxx.dao.po
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true